# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce94f6e9d6c03147310c68e60f13ec2f5917ba16bd0cae01bb0f0ac26b49a60c411c47197a61aae178630394358a0266adc96b4cd0cc6c776cd8cac616fa7152

test:
  secret_key_base: 4e9c7bdb320d67dc8d3c9a1ad3434b1c8d30cb7d85c3bc13d93c77512e4e29b3ce464d9d3ed0d784aa8be4a62c76a33ae4973629cd7cba0a185ff5fac62acfe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
